# Generated by Django 5.2 on 2025-07-04 07:31

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPurchaseAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto original')),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto pendiente')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de inicio')),
                ('payment_frequency', models.CharField(choices=[('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('custom', 'Personalizado')], default='monthly', max_length=20, verbose_name='Frecuencia de pago')),
                ('next_payment_date', models.DateField(blank=True, null=True, verbose_name='Próxima fecha de pago')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monto acordado para cada pago periódico', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Monto de pago acordado')),
                ('grace_days', models.PositiveIntegerField(default=3, help_text='Días de gracia antes de enviar recordatorio', verbose_name='Días de gracia')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la cuenta de crédito está activa', verbose_name='Activo')),
                ('notes', models.TextField(blank=True, default='', help_text='Observaciones adicionales sobre el crédito', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('purchase_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_account', to='purchases.purchaseorder', verbose_name='Orden de compra')),
            ],
            options={
                'verbose_name': 'Cuenta de crédito de compra',
                'verbose_name_plural': 'Cuentas de crédito de compra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditPurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Monto pagado')),
                ('payment_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de pago')),
                ('payment_method', models.CharField(blank=True, default='', help_text='Efectivo, transferencia, cheque, etc.', max_length=50, verbose_name='Método de pago')),
                ('reference_number', models.CharField(blank=True, default='', help_text='Número de transferencia, cheque, etc.', max_length=100, verbose_name='Número de referencia')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='credits.creditpurchaseaccount', verbose_name='Cuenta de crédito')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_purchase_payments', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Abono de crédito de compra',
                'verbose_name_plural': 'Abonos de crédito de compra',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditPurchaseReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('overdue', 'Pago Vencido'), ('upcoming', 'Próximo Pago'), ('balance_ok', 'Saldo al Día'), ('payment_received', 'Pago Recibido')], max_length=20, verbose_name='Tipo de recordatorio')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('scheduled_date', models.DateTimeField(verbose_name='Fecha programada')),
                ('sent_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('message_content', models.TextField(verbose_name='Contenido del mensaje')),
                ('whatsapp_message_id', models.CharField(blank=True, default='', max_length=100, verbose_name='ID del mensaje de WhatsApp')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Mensaje de error')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Intentos de reenvío')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='credits.creditpurchaseaccount', verbose_name='Cuenta de crédito')),
            ],
            options={
                'verbose_name': 'Recordatorio de crédito',
                'verbose_name_plural': 'Recordatorios de crédito',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
