# Generated by Django 5.2 on 2025-07-06 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_creditpurchaseaccount_creditpurchasepayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditaccount',
            name='installment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto acordado para cada cuota', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Monto de cuota'),
        ),
        migrations.AddField(
            model_name='creditaccount',
            name='installments_count',
            field=models.PositiveIntegerField(blank=True, help_text='Número total de cuotas acordadas', null=True, verbose_name='Número de cuotas'),
        ),
        migrations.AddField(
            model_name='creditaccount',
            name='next_payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Próxima fecha de pago'),
        ),
        migrations.AddField(
            model_name='creditaccount',
            name='payment_frequency',
            field=models.CharField(choices=[('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('custom', 'Personalizado')], default='monthly', help_text='Frecuencia de pago acordada para las cuotas', max_length=20, verbose_name='Frecuencia de pago'),
        ),
    ]
