# Generated by Django 5.2 on 2025-07-06 03:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0003_creditaccount_installment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditaccount',
            name='initial_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monto del pago inicial al crear el crédito', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pago inicial'),
        ),
    ]
