# Generated by Django 5.2 on 2025-07-16 01:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0004_creditaccount_initial_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditaccount',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='creditpayment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='creditpurchaseaccount',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de inicio'),
        ),
    ]
