# Generated by Django 5.2 on 2025-05-31 06:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0003_alter_product_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre completo del proveedor o empresa', max_length=200, verbose_name='Nombre del proveedor')),
                ('contact_name', models.CharField(blank=True, help_text='Persona de contacto en el proveedor', max_length=100, null=True, verbose_name='Nombre del contacto')),
                ('phone', models.CharField(blank=True, help_text='Número de teléfono del proveedor', max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico del proveedor', max_length=100, null=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Marca del producto ofrecida por este proveedor', max_length=100, verbose_name='Marca')),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Precio al que el proveedor vende este producto', max_digits=12, verbose_name='Precio de compra')),
                ('valid_from', models.DateField(default=django.utils.timezone.now, help_text='Fecha desde la cual es válido este precio', verbose_name='Válido desde')),
                ('valid_to', models.DateField(blank=True, help_text='Fecha hasta la cual es válido este precio (opcional)', null=True, verbose_name='Válido hasta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('product', models.ForeignKey(help_text='Producto al que se refiere esta opción de compra', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_options', to='catalogs.product', verbose_name='Producto')),
                ('supplier', models.ForeignKey(help_text='Proveedor que ofrece este producto', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_options', to='suppliers.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Opción de compra',
                'verbose_name_plural': 'Opciones de compra',
                'ordering': ['product__name', 'supplier__name', '-valid_from'],
                'unique_together': {('product', 'supplier', 'brand', 'valid_from')},
            },
        ),
    ]
