# Generated by Django 5.2 on 2025-05-31 06:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseoption',
            name='valid_from',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Fecha desde la cual es válido este precio', verbose_name='Válido desde'),
        ),
    ]
