"""
Django settings for unidental project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv # Importa load_dotenv
from decouple import config # Added
import dj_database_url
import sys # Added for checking 'test' in sys.argv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(os.path.join(BASE_DIR, '.env')) # Busca el .env en la carpeta raíz del proyecto


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS_STRING = config('ALLOWED_HOSTS', default='127.0.0.1,localhost')
ALLOWED_HOSTS = [s.strip() for s in ALLOWED_HOSTS_STRING.split(',')]

# Agregar dominios de Railway y Render automáticamente si no está en DEBUG
if not DEBUG:
    # Permitir todos los subdominios de Railway
    ALLOWED_HOSTS.extend([
        '.railway.app',
        '.up.railway.app', 
        'unidental-backend-production.up.railway.app'
    ])
    
    # Permitir dominios de Render
    ALLOWED_HOSTS.extend([
        '.onrender.com',
        'unidental-backend.onrender.com'
    ])
    
    # En desarrollo local también permitir
    if '127.0.0.1' not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.extend(['127.0.0.1', 'localhost'])
# CSRF Configuration for HTTPS
# Asegúrate de que la URL de tu sitio de producción esté aquí
# Puedes leerla de una variable de entorno si cambia entre entornos
CSRF_TRUSTED_ORIGINS_STRING = config('CSRF_TRUSTED_ORIGINS', default='https://unidental-backend-production.up.railway.app')
CSRF_TRUSTED_ORIGINS = [s.strip() for s in CSRF_TRUSTED_ORIGINS_STRING.split(',')]

# Para confiar en la cabecera X-Forwarded-Proto de proxies como los de Railway
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Configuración de Cookies para producción HTTPS
# Estas se activarán si DEBUG es False, o si las variables de entorno las fuerzan a True
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=not DEBUG, cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=not DEBUG, cast=bool)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'drf_yasg',
    'djoser',
    'corsheaders',
    'django_filters',
    'core',
    'catalogs',
    'credits',
    'sales',
    'deliveries',
    'inventory',
    'purchases',
    'suppliers',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # o el dominio de tu frontend real
    "https://unidental-frontend.vercel.app",
    "https://pruebas-frontend-unidental.vercel.app",
]
ROOT_URLCONF = 'unidental.urls'

CORS_ALLOW_CREDENTIALS = True


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'unidental.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Configuración simplificada para tests
if 'test' in sys.argv:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    }
else:
    # Para desarrollo/producción, usar configuración manual más segura
    DATABASE_URL = config('DATABASE_URL', default='')
    
    if DATABASE_URL.startswith('postgres://'):
        # Convertir postgres:// a postgresql:// para evitar warnings
        DATABASE_URL = DATABASE_URL.replace('postgres://', 'postgresql://', 1)
    
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME', default='unidental'),
            'USER': config('DB_USER', default='postgres'),
            'PASSWORD': config('DB_PASSWORD', default=''),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
            'OPTIONS': {
                'sslmode': 'require' if not DEBUG else 'prefer',
            },
        }
    }
    
    # Si hay DATABASE_URL, usarlo para sobreescribir
    if DATABASE_URL:
        import dj_database_url
        db_from_url = dj_database_url.parse(DATABASE_URL)
        DATABASES['default'].update(db_from_url)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Directorio donde collectstatic reunirá todos los archivos estáticos para producción.
STATIC_ROOT = BASE_DIR / 'staticfiles' # O también os.path.join(BASE_DIR, 'staticfiles')

# Opcional: Directorios adicionales donde Django buscará archivos estáticos (además de los de cada app)
# STATICFILES_DIRS = [
#     BASE_DIR / "static", # Si tienes una carpeta 'static' general en la raíz del proyecto
# ]

# Configuración para WhiteNoise (optimización para servir estáticos)
# Asegúrate de que DEBUG = False en producción para que esto tenga efecto.
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    }
}
# Si estás usando una versión de Django anterior a 4.2, en lugar de STORAGES,
# usarías la siguiente línea:
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25, # Número de ítems por página por defecto
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ] + (['rest_framework.renderers.BrowsableAPIRenderer'] if DEBUG else []),
}

# Configuración de logging optimizada para producción
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple' if DEBUG else 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'django.log',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO' if DEBUG else 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO' if DEBUG else 'WARNING',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'ERROR',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

# Configuraciones de caché para Railway
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 300,  # 5 minutos
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        }
    }
}

# Configuración de sesiones optimizada
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
SESSION_CACHE_ALIAS = 'default'

# Optimizaciones de base de datos para Railway
if not DEBUG:
    # Configuraciones adicionales para producción
    DATABASE_CONNECTION_POOL_SIZE = config('DATABASE_CONNECTION_POOL_SIZE', default=5, cast=int)
    DATABASE_MAX_CONNECTIONS = config('DATABASE_MAX_CONNECTIONS', default=10, cast=int)
    
    # Actualizar configuración de base de datos para producción
    DATABASES['default'].update({
        'CONN_MAX_AGE': config('CONN_MAX_AGE', default=600, cast=int),
        'OPTIONS': {
            'connect_timeout': 10,
        }
    })

# Configuración de archivos estáticos optimizada
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Configuración de compresión para WhiteNoise
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = DEBUG

# Configuraciones de seguridad para Railway
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Configuración de timeout para requests
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB

# Djoser settings (opcional, para personalización)
DJOSER = {
    'PASSWORD_RESET_CONFIRM_URL': 'password/reset/confirm/{uid}/{token}',
    'USERNAME_RESET_CONFIRM_URL': 'username/reset/confirm/{uid}/{token}',
    'ACTIVATION_URL': 'activate/{uid}/{token}',
    'SEND_ACTIVATION_EMAIL': False, # Cambiar a True si quieres activación por email
    'SEND_CONFIRMATION_EMAIL': False,
    'PASSWORD_RESET_SHOW_EMAIL_NOT_FOUND': True,
    'PASSWORD_RESET_CONFIRM_RETYPE': True,
    'SET_PASSWORD_RETYPE': True,
    'USERNAME_RESET_CONFIRM_RETYPE': True,
    'EMAIL': {
        'password_reset': 'core.email.PasswordResetEmail',
    },
    # 'SERIALIZERS': {
    #     'user_create': 'your_app.serializers.UserCreateSerializer', # Ejemplo para personalizar
    #     'user': 'your_app.serializers.UserSerializer',
    #     'current_user': 'your_app.serializers.UserSerializer',
    # },
    # 'USER_ID_FIELD': 'id', # o el campo que uses como ID de usuario
    # 'LOGIN_FIELD': 'email', # o 'username'
}

# Email Configuration
# ====================
if DEBUG:
    # En desarrollo: mostrar emails en la consola
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    # En producción: usar SMTP
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
    EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
    EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
    EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
    EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

# Configuraciones generales de email
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@unidental.com')
SERVER_EMAIL = config('SERVER_EMAIL', default='admin@unidental.com')
EMAIL_SUBJECT_PREFIX = '[UNIDENTAL] '

# Configuración adicional para emails HTML
EMAIL_USE_LOCALTIME = True
