[pytest]
# Apuntar a un archivo de settings específico para los tests.
# Esta es la forma más robusta de separar la configuración de test de la de producción.
DJANGO_SETTINGS_MODULE = unidental.test_settings
python_files = tests.py test_*.py *_tests.py

# Sobrescribir la configuración de la base de datos para los tests
# Esta es la forma robusta y estándar de hacerlo con pytest-django.
# Forzará a Django a usar una base de datos SQLite en memoria para todos los tests,
# ignorando por completo la configuración de PostgreSQL en settings.py.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',
    }
}