# Generated by Django 5.2 on 2025-05-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='Código de barras del producto (EAN, UPC, etc.) si aplica.', max_length=100, null=True, unique=True, verbose_name='Código de Barras'),
        ),
    ]
