# Generated by Django 5.2 on 2025-05-29 02:48

import catalogs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_product_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(help_text='Formato: CATEGORIA-SUBCATEGORIA-TIPO-SECUENCIAL (ej: ART-PRE-BIO-001)', max_length=50, unique=True, validators=[catalogs.validators.validate_sku], verbose_name='SKU (Código Único de Producto)'),
        ),
    ]
