# Generated by Django 5.2 on 2025-06-15 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('simple', 'Producto Simple'), ('composite', 'Producto Compuesto/Kit'), ('component', 'Componente de Kit')], default='simple', help_text='Simple: producto individual, Compuesto: contiene otros productos, Componente: parte de un kit', max_length=20, verbose_name='Tipo de Producto'),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_batch_control',
            field=models.BooleanField(default=False, help_text='Marcar si este producto requiere seguimiento por lotes (fechas de vencimiento)', verbose_name='Requiere Control de Lotes'),
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(help_text='Identificación única del lote del fabricante', max_length=100, verbose_name='Número de Lote')),
                ('manufacturing_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Fabricación')),
                ('expiry_date', models.DateField(help_text='Fecha en que el lote expira', verbose_name='Fecha de Vencimiento')),
                ('supplier_reference', models.CharField(blank=True, help_text='Referencia o código del proveedor para este lote', max_length=100, null=True, verbose_name='Referencia del Proveedor')),
                ('notes', models.TextField(blank=True, help_text='Observaciones adicionales sobre el lote', null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='catalogs.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Lote de Producto',
                'verbose_name_plural': 'Lotes de Productos',
                'ordering': ['expiry_date', 'batch_number'],
                'unique_together': {('product', 'batch_number')},
            },
        ),
        migrations.CreateModel(
            name='ProductComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Cantidad del componente contenida en una unidad del producto compuesto', verbose_name='Cantidad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('component_product', models.ForeignKey(help_text='El producto individual que está contenido en el kit', on_delete=django.db.models.deletion.CASCADE, related_name='component_of', to='catalogs.product', verbose_name='Producto Componente')),
                ('composite_product', models.ForeignKey(help_text='El producto kit/caja que contiene otros productos', on_delete=django.db.models.deletion.CASCADE, related_name='composite_components', to='catalogs.product', verbose_name='Producto Compuesto')),
            ],
            options={
                'verbose_name': 'Componente de Producto',
                'verbose_name_plural': 'Componentes de Productos',
                'ordering': ['composite_product__name', 'component_product__name'],
                'unique_together': {('composite_product', 'component_product')},
            },
        ),
    ]
