# Generated by Django 5.2 on 2025-06-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_product_product_type_product_requires_batch_control_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_expiry_days_threshold',
            field=models.PositiveIntegerField(blank=True, help_text='Número mínimo de días antes del vencimiento para que un lote sea considerado aceptable.', null=True, verbose_name='Umbral Mínimo de Días de Vencimiento'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_stock_threshold',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad mínima de stock aceptable para este producto en una sede.', null=True, verbose_name='Umbral Mínimo de Stock'),
        ),
    ]
