# Generated by Django 5.2 on 2025-07-02 00:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0005_product_min_expiry_days_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de lista o PVP recomendado', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de venta'),
        ),
    ]
