# Generated by Django 5.2 on 2025-07-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0006_product_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('simple', 'Producto Simple'), ('boxed_component', 'Caja/Empaque de componente único'), ('mixed_kit', 'Kit Mixto de varios productos'), ('composite', 'Producto Compuesto/Kit (LEGACY)'), ('component', 'Componente individual de Kit')], default='simple', help_text='Simple: producto individual, Compuesto: contiene otros productos, Componente: parte de un kit', max_length=20, verbose_name='Tipo de Producto'),
        ),
    ]
