# Generated by Django 5.2 on 2025-07-13 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0007_alter_product_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código único de 3 letras para la categoría del SKU (ej: ART).', max_length=3, unique=True, verbose_name='Código de Categoría SKU')),
                ('name', models.CharField(help_text='Nombre descriptivo de la categoría del SKU.', max_length=100, verbose_name='Nombre de Categoría SKU')),
            ],
            options={
                'verbose_name': 'Categoría de SKU',
                'verbose_name_plural': 'Categorías de SKU',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SkuSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código de 3 letras para la subcategoría (único por categoría).', max_length=3, verbose_name='Código de Subcategoría SKU')),
                ('name', models.CharField(help_text='Nombre descriptivo de la subcategoría del SKU.', max_length=100, verbose_name='Nombre de Subcategoría SKU')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='catalogs.skucategory', verbose_name='Categoría de SKU')),
            ],
            options={
                'verbose_name': 'Subcategoría de SKU',
                'verbose_name_plural': 'Subcategorías de SKU',
                'ordering': ['category__code', 'code'],
                'unique_together': {('category', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SkuType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código de 3 letras para el tipo (único por subcategoría).', max_length=3, verbose_name='Código de Tipo de SKU')),
                ('name', models.CharField(help_text='Nombre descriptivo del tipo de SKU.', max_length=100, verbose_name='Nombre de Tipo de SKU')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='catalogs.skusubcategory', verbose_name='Subcategoría de SKU')),
            ],
            options={
                'verbose_name': 'Tipo de SKU',
                'verbose_name_plural': 'Tipos de SKU',
                'ordering': ['subcategory__category__code', 'subcategory__code', 'code'],
                'unique_together': {('subcategory', 'code')},
            },
        ),
    ]
