# Generated by Django 5.2 on 2025-07-15 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0008_skucategory_skusubcategory_skutype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_rate', models.PositiveIntegerField(help_text='Cantidad del producto destino que se obtiene por cada unidad del producto origen', verbose_name='Factor de Conversión')),
                ('is_reversible', models.BooleanField(default=False, help_text='Si se puede hacer la conversión inversa (ej: 5 blisters → 1 caja)', verbose_name='¿Es Reversible?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_product', models.ForeignKey(help_text='Producto que se convierte (ej: Caja)', on_delete=django.db.models.deletion.CASCADE, related_name='conversion_from', to='catalogs.product', verbose_name='Producto Origen')),
                ('to_product', models.ForeignKey(help_text='Producto resultante de la conversión (ej: Blisters)', on_delete=django.db.models.deletion.CASCADE, related_name='conversion_to', to='catalogs.product', verbose_name='Producto Destino')),
            ],
            options={
                'verbose_name': 'Conversión de Producto',
                'verbose_name_plural': 'Conversiones de Productos',
                'ordering': ['from_product__name', 'to_product__name'],
                'unique_together': {('from_product', 'to_product')},
            },
        ),
    ]
