# Generated by Django 5.2 on 2025-06-03 06:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_alter_inventorymovement_notes_alter_location_address_and_more'),
        ('suppliers', '0002_alter_purchaseoption_valid_from'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(default=django.utils.timezone.localdate, help_text='Fecha en que se realizó la orden', verbose_name='Fecha de orden')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('received', 'Recibida'), ('canceled', 'Cancelada')], default='pending', help_text='Estado actual de la orden de compra', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, default='', help_text='Observaciones o notas adicionales sobre la orden', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que creó la orden', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('destination', models.ForeignKey(help_text='Ubicación donde se recibirán los productos', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='inventory.location', verbose_name='Destino')),
                ('supplier', models.ForeignKey(help_text='Proveedor al cual se realiza la orden de compra', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='suppliers.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Orden de compra',
                'verbose_name_plural': 'Órdenes de compra',
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.PositiveIntegerField(help_text='Cantidad de unidades solicitadas', verbose_name='Cantidad solicitada')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Precio por unidad al momento de la orden', max_digits=12, verbose_name='Precio unitario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('order', models.ForeignKey(help_text='Orden de compra a la que pertenece este item', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaseorder', verbose_name='Orden de compra')),
                ('purchase_option', models.ForeignKey(help_text='Opción de compra (producto + proveedor + marca + precio)', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='suppliers.purchaseoption', verbose_name='Opción de compra')),
            ],
            options={
                'verbose_name': 'Item de orden de compra',
                'verbose_name_plural': 'Items de orden de compra',
                'ordering': ['order', 'purchase_option__product__name'],
                'unique_together': {('order', 'purchase_option')},
            },
        ),
    ]
