# Generated by Django 5.2 on 2025-06-02 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0003_alter_product_sku'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('type', models.CharField(choices=[('sede', 'Sede'), ('bodega', 'Bodega')], max_length=20, verbose_name='Tipo')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Entrada'), ('out', 'Salida')], max_length=10, verbose_name='Tipo de movimiento')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de ocurrencia')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='catalogs.product', verbose_name='Producto')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.location', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_locations', to='catalogs.product', verbose_name='Producto')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='inventory.location', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Stock de inventario',
                'verbose_name_plural': 'Stock de inventario',
                'ordering': ['product__name', 'location__name'],
                'unique_together': {('product', 'location')},
            },
        ),
    ]
