# Generated by Django 5.2 on 2025-06-15 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_product_product_type_product_requires_batch_control_and_more'),
        ('inventory', '0002_alter_inventorymovement_notes_alter_location_address_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventorystock',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Lote específico (solo para productos que requieren control de lotes)', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.productbatch', verbose_name='Lote'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='related_composite_movement',
            field=models.ForeignKey(blank=True, help_text='Movimiento del producto padre que generó este movimiento', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorymovement', verbose_name='Movimiento de Producto Compuesto Relacionado'),
        ),
        migrations.AddField(
            model_name='inventorystock',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Lote específico (solo para productos que requieren control de lotes)', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.productbatch', verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Entrada'), ('out', 'Salida'), ('composite_conversion', 'Conversión de Producto Compuesto')], max_length=20, verbose_name='Tipo de movimiento'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorystock',
            unique_together={('product', 'location', 'batch')},
        ),
    ]
