# Generated by Django 5.2 on 2025-07-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventorystock_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Entrada'), ('out', 'Salida'), ('composite_conversion', 'Conversión de Producto Compuesto'), ('composite_assembly', 'Ensamblaje de Compuesto')], max_length=20, verbose_name='Tipo de movimiento'),
        ),
    ]
