# Generated by Django 5.2 on 2025-07-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventorymovement_movement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='completed', max_length=20, verbose_name='Estado'),
        ),
    ]
