# Generated by Django 5.2 on 2025-07-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventorymovement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='is_internal_transfer',
            field=models.BooleanField(default=False, help_text='Marcar si este movimiento es una transferencia entre bodegas/sedes.', verbose_name='Transferencia Interna'),
        ),
    ]
