# Generated by Django 5.2 on 2025-07-11 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventorymovement_is_internal_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='destination_location',
            field=models.ForeignKey(blank=True, help_text='Ubicación de destino para transferencias internas.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='inventory.location', verbose_name='Ubicación de Destino'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='related_transfer_movement',
            field=models.ForeignKey(blank=True, help_text='Vincula el movimiento de entrada con el de salida en una transferencia.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfer_movement', to='inventory.inventorymovement', verbose_name='Movimiento de Transferencia Relacionado'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='related_composite_movement',
            field=models.ForeignKey(blank=True, help_text='Movimiento del producto padre que generó este movimiento', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component_movements', to='inventory.inventorymovement', verbose_name='Movimiento de Producto Compuesto Relacionado'),
        ),
    ]
