# Generated by Django 5.2 on 2025-07-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventorymovement_destination_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='is_conversion',
            field=models.BooleanField(default=False, help_text='Marcar si este movimiento es resultado de una conversión manual entre productos.', verbose_name='Es Conversión Manual'),
        ),
    ]
