# Generated by Django 5.2 on 2025-07-29 01:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ('purchases', '0001_initial'),   # ← agregar esta línea
    ('inventory', '0008_inventorymovement_is_conversion'),
    ('sales', '0007_alter_sale_sale_type'),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
]

    operations = [
        migrations.CreateModel(
            name='Cashes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo actual de la caja (calculado automáticamente)', max_digits=15, verbose_name='Saldo Actual')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la caja está activa para operaciones', verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('location', models.OneToOneField(help_text='Sede a la que pertenece esta caja', on_delete=django.db.models.deletion.CASCADE, related_name='cash', to='inventory.location', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['location__name'],
            },
        ),
        migrations.CreateModel(
            name='Movements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso'), ('ajuste', 'Ajuste')], help_text='Tipo de movimiento: ingreso, egreso o ajuste', max_length=10, verbose_name='Tipo de Movimiento')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto del movimiento (siempre positivo)', max_digits=15, verbose_name='Monto')),
                ('reference_type', models.CharField(choices=[('venta', 'Venta'), ('compra', 'Compra'), ('ajuste_manual', 'Ajuste Manual'), ('transferencia', 'Transferencia'), ('otro', 'Otro')], help_text='Indica el origen del movimiento', max_length=20, verbose_name='Tipo de Referencia')),
                ('notes', models.TextField(blank=True, default='', help_text='Motivo o descripción del movimiento', verbose_name='Notas')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('cancelled', 'Anulado')], default='active', help_text='Estado del movimiento', max_length=10, verbose_name='Estado')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de anulación')),
                ('cancellation_reason', models.TextField(blank=True, default='', help_text='Razón por la cual se anuló el movimiento', verbose_name='Motivo de Anulación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('cancelled_by', models.ForeignKey(blank=True, help_text='Usuario que anuló el movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_cash_movements', to=settings.AUTH_USER_MODEL, verbose_name='Anulado por')),
                ('cash', models.ForeignKey(help_text='Caja donde se registra el movimiento', on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='cash.cashes', verbose_name='Caja')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que creó el movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cash_movements', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('purchase_order', models.ForeignKey(blank=True, help_text='Orden de compra asociada a este movimiento (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='purchases.purchaseorder', verbose_name='Orden de Compra Relacionada')),
                ('sale', models.ForeignKey(blank=True, help_text='Venta asociada a este movimiento (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='sales.sale', verbose_name='Venta Relacionada')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto a transferir', max_digits=15, verbose_name='Monto')),
                ('notes', models.TextField(blank=True, default='', help_text='Motivo o descripción de la transferencia', verbose_name='Notas')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de completación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cash_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('destination_cash', models.ForeignKey(help_text='Caja donde llega el dinero', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='cash.cashes', verbose_name='Caja Destino')),
                ('destination_movement', models.ForeignKey(blank=True, help_text='Movimiento de ingreso en la caja destino', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_transfer', to='cash.movements', verbose_name='Movimiento de Entrada')),
                ('origin_cash', models.ForeignKey(help_text='Caja desde donde sale el dinero', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='cash.cashes', verbose_name='Caja Origen')),
                ('origin_movement', models.ForeignKey(blank=True, help_text='Movimiento de egreso en la caja origen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_transfer', to='cash.movements', verbose_name='Movimiento de Salida')),
            ],
            options={
                'verbose_name': 'Transferencia de Caja',
                'verbose_name_plural': 'Transferencias de Caja',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='movements',
            index=models.Index(fields=['cash', 'status'], name='cash_cashmo_cash_id_590b7e_idx'),
        ),
        migrations.AddIndex(
            model_name='movements',
            index=models.Index(fields=['movement_type', 'created_at'], name='cash_cashmo_movemen_be744e_idx'),
        ),
        migrations.AddIndex(
            model_name='movements',
            index=models.Index(fields=['reference_type'], name='cash_cashmo_referen_77a2e7_idx'),
        ),
        migrations.AddIndex(
            model_name='transfers',
            index=models.Index(fields=['status', 'created_at'], name='cash_cashtr_status_62558e_idx'),
        ),
        migrations.AddIndex(
            model_name='transfers',
            index=models.Index(fields=['origin_cash', 'destination_cash'], name='cash_cashtr_origin__339e90_idx'),
        ),
    ]
