# Generated by Django 5.2 on 2025-07-26 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cash',
            table='cash_cashes',
        ),
        migrations.AlterModelTable(
            name='cashmovement',
            table='cash_movements',
        ),
        migrations.AlterModelTable(
            name='cashtransfer',
            table='cash_transfers',
        ),
    ]
