# Generated by Django 5.2 on 2025-07-26 20:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_rename_tables_to_plural'),
        ('inventory', '0008_inventorymovement_is_conversion'),
        ('purchases', '0002_purchaseorderpayment'),
        ('sales', '0007_alter_sale_sale_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cash',
            new_name='Cashes',
        ),
        migrations.RenameModel(
            old_name='CashMovement',
            new_name='Movements',
        ),
        migrations.RenameModel(
            old_name='CashTransfer',
            new_name='Transfers',
        ),
        migrations.AlterModelTable(
            name='cashes',
            table=None,
        ),
        migrations.AlterModelTable(
            name='movements',
            table=None,
        ),
        migrations.AlterModelTable(
            name='transfers',
            table=None,
        ),
    ]
