# Generated by Django 5.2 on 2025-06-11 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventorymovement_notes_alter_location_address_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='location',
            field=models.ForeignKey(default=5, help_text='Sede donde se realizó la venta', on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='inventory.location', verbose_name='Sede de venta'),
            preserve_default=False,
        ),
    ]
