# Generated by Django 5.2 on 2025-06-12 08:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_alter_product_sku'),
        ('inventory', '0002_alter_inventorymovement_notes_alter_location_address_and_more'),
        ('sales', '0002_sale_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de devolución')),
                ('reason', models.CharField(choices=[('defective', 'Producto defectuoso'), ('wrong_item', 'Producto incorrecto'), ('customer_change', 'Cambio de opinión del cliente'), ('damaged', 'Producto dañado'), ('expired', 'Producto vencido'), ('other', 'Otro')], max_length=20, verbose_name='Motivo de devolución')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas adicionales')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto total devuelto')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='sales.customer', verbose_name='Cliente')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='inventory.location', verbose_name='Sede de devolución')),
                ('original_sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.sale', verbose_name='Venta original')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'ordering': ['-return_date'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_returned', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad devuelta')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='catalogs.product', verbose_name='Producto')),
                ('return_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.return', verbose_name='Devolución')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='sales.saleitem', verbose_name='Item de venta original')),
            ],
            options={
                'verbose_name': 'Item de devolución',
                'verbose_name_plural': 'Items de devolución',
                'ordering': ['id'],
            },
        ),
    ]
