# Generated by Django 5.2 on 2025-06-20 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_product_product_type_product_requires_batch_control_and_more'),
        ('sales', '0003_return_returnitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Lote específico (requerido solo para productos con control de lotes)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='catalogs.productbatch', verbose_name='Lote'),
        ),
    ]
