# Generated by Django 5.2 on 2025-07-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_saleitem_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='customer',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de cumpleaños'),
        ),
        migrations.AddField(
            model_name='customer',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Contacto de emergencia'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
    ]
