# Generated by Django 5.2 on 2025-07-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_customer_address_customer_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('mayorista', 'Mayorista'), ('credit', 'Crédito')], default='normal', max_length=20, verbose_name='Tipo de venta'),
        ),
    ]
