# Generated by Django 5.2 on 2025-07-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_sale_sale_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(choices=[('normal', 'Efectivo'), ('card', 'Tarjeta'), ('credit', 'Crédito')], default='normal', max_length=20, verbose_name='Tipo de venta'),
        ),
    ]
