# Generated by Django 5.2 on 2025-06-03 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_alter_inventorymovement_notes_alter_location_address_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_transit', 'En Tránsito'), ('delivered', 'Entregado')], default='pending', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dest_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries_destination', to='inventory.location', verbose_name='Ubicación de Destino')),
                ('origin_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries_origin', to='inventory.location', verbose_name='Ubicación de Origen')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='sales.sale', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='deliveries__status_bdfe1b_idx'), models.Index(fields=['shipped_at'], name='deliveries__shipped_1936dd_idx'), models.Index(fields=['delivered_at'], name='deliveries__deliver_30d5f2_idx')],
            },
        ),
    ]
